name: dom_repeat_model
environment:
  sdk: ">=1.12.0 <2.0.0"

dependencies:
  polymer: ^1.0.0-rc.6
  polymer_elements: ^1.0.0-rc.3
  reflectable: ^0.3.3
  web_components: ^0.12.0+3
#  http_parser: ^1.1.0

dev_dependencies:
  test: ^0.12.3+9

transformers:
- web_components:
    entry_points:
    - web/index.html

- reflectable:
    entry_points:
    - web/index.dart

- test/pub_serve:
    $include: test/**_test{.*,}.dart

- $dart2js:
    minify: true
    $include: '**/*.bootstrap.initialize.dart'
    #$include: "**/*.polymer.bootstrap.dart"

